module Scalar
  module Models
    type registry_list_api_documents_params =
      { namespace: String } & Scalar::Internal::Type::request_parameters

    class RegistryListAPIDocumentsParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      attr_accessor namespace: String

      def initialize: (
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        request_options: Scalar::RequestOptions
      }
    end
  end
end
