module Scalar
  module Models
    type value400 = { code: String, message: String }

    class Value400 < Scalar::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor message: String

      def initialize: (code: String, message: String) -> void

      def to_hash: -> { code: String, message: String }
    end
  end
end
