module Scalar
  module Models
    type registry_create_api_document_version_params =
      {
        namespace: String,
        slug: String,
        document: String,
        version: String,
        force: bool,
        last_known_version_sha: String
      }
      & Scalar::Internal::Type::request_parameters

    class RegistryCreateAPIDocumentVersionParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      attr_accessor namespace: String

      attr_accessor slug: String

      attr_accessor document: String

      attr_accessor version: String

      attr_reader force: bool?

      def force=: (bool) -> bool

      attr_reader last_known_version_sha: String?

      def last_known_version_sha=: (String) -> String

      def initialize: (
        namespace: String,
        slug: String,
        document: String,
        version: String,
        ?force: bool,
        ?last_known_version_sha: String,
        ?request_options: Scalar::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        slug: String,
        document: String,
        version: String,
        force: bool,
        last_known_version_sha: String,
        request_options: Scalar::RequestOptions
      }
    end
  end
end
