module Scalar
  module Models
    type scalar_doc_list_guides_params =
      {  } & Scalar::Internal::Type::request_parameters

    class ScalarDocListGuidesParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      def initialize: (?request_options: Scalar::request_opts) -> void

      def to_hash: -> { request_options: Scalar::RequestOptions }
    end
  end
end
