# frozen_string_literal: true

# Code generated by Scalar SDK Generator. DO NOT EDIT.
require "json"
require "stringio"
require "time"

root =
  File.exist?(File.join(__dir__, "lib", "scalar_api_ruby.rb")) ? __dir__ : File.expand_path("..", __dir__)
$LOAD_PATH.unshift(File.join(root, "lib"))
require "scalar_api_ruby"

# Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
# Run it from this repo with `ruby tests/smoke-test.rb`. The generator also runs this file
# against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
client = Scalar::Client.new(max_retries: 2, timeout: 10)

cases = [
  {
    operation: "createApiDocument",
    method: "POST",
    path: "/v1/apis/{namespace}",
    label: "required params",
    run: -> do
      client.registry.create_api_document("namespace", {document: "", slug: "", title: "", version: "x"})
    end
  },
  {
    operation: "createApiDocument",
    method: "POST",
    path: "/v1/apis/{namespace}",
    label: "all params",
    run: -> do
      client.registry.create_api_document(
        "namespace",
        {document: "", slug: "", title: "", version: "x", description: "", is_private: false, ruleset: ""}
      )
    end
  },
  {
    operation: "createApiDocumentAccessGroup",
    method: "POST",
    path: "/v1/apis/{namespace}/{slug}/access-group",
    run: -> do
      client.registry.create_api_document_access_group(
        "slug",
        {access_group_slug: "x", namespace: "namespace"}
      )
    end
  },
  {
    operation: "createApiDocumentVersion",
    method: "POST",
    path: "/v1/apis/{namespace}/{slug}/version",
    label: "required params",
    run: -> do
      client.registry.create_api_document_version(
        "slug",
        {namespace: "namespace", document: "", version: "x"}
      )
    end
  },
  {
    operation: "createApiDocumentVersion",
    method: "POST",
    path: "/v1/apis/{namespace}/{slug}/version",
    label: "all params",
    run: -> do
      client.registry.create_api_document_version(
        "slug",
        {namespace: "namespace", document: "", version: "x", force: false}
      )
    end
  },
  {
    operation: "deleteApiDocument",
    method: "DELETE",
    path: "/v1/apis/{namespace}/{slug}",
    run: -> { client.registry.delete_api_document("slug", {namespace: "namespace"}) }
  },
  {
    operation: "deleteApiDocumentAccessGroup",
    method: "DELETE",
    path: "/v1/apis/{namespace}/{slug}/access-group",
    run: -> do
      client.registry.delete_api_document_access_group(
        "slug",
        {access_group_slug: "x", namespace: "namespace"}
      )
    end
  },
  {
    operation: "deleteApiDocumentVersion",
    method: "DELETE",
    path: "/v1/apis/{namespace}/{slug}/version/{semver}",
    run: -> do
      client.registry.delete_api_document_version("semver", {namespace: "namespace", slug: "slug"})
    end
  },
  {
    operation: "listAllApiDocuments",
    method: "GET",
    path: "/v1/apis",
    run: -> { client.registry.list_all_api_documents }
  },
  {
    operation: "listApiDocumentVersionMetadata",
    method: "GET",
    path: "/v1/apis/{namespace}/{slug}/version/{semver}/metadata",
    run: -> do
      client.registry.list_api_document_version_metadata("semver", {namespace: "namespace", slug: "slug"})
    end
  },
  {
    operation: "listApiDocuments",
    method: "GET",
    path: "/v1/apis/{namespace}",
    run: -> { client.registry.list_api_documents("namespace") }
  },
  {
    operation: "retrieveApiDocumentVersion",
    method: "GET",
    path: "/v1/apis/{namespace}/{slug}/version/{semver}",
    run: -> do
      client.registry.retrieve_api_document_version("semver", {namespace: "namespace", slug: "slug"})
    end
  },
  {
    operation: "updateApiDocument",
    method: "PATCH",
    path: "/v1/apis/{namespace}/{slug}",
    label: "required params",
    run: -> { client.registry.update_api_document("slug", {namespace: "namespace"}) }
  },
  {
    operation: "updateApiDocument",
    method: "PATCH",
    path: "/v1/apis/{namespace}/{slug}",
    label: "all params",
    run: -> do
      client.registry.update_api_document(
        "slug",
        {namespace: "namespace", description: "", is_private: false, ruleset: "", title: ""}
      )
    end
  },
  {
    operation: "updateApiDocumentVersion",
    method: "PATCH",
    path: "/v1/apis/{namespace}/{slug}/version/{semver}",
    run: -> do
      client.registry.update_api_document_version(
        "semver",
        {namespace: "namespace", slug: "slug", document: ""}
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/schemas/{namespace}",
    label: "required params",
    run: -> { client.schemas.create("namespace", {document: "", slug: "", title: "", version: "x"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/schemas/{namespace}",
    label: "all params",
    run: -> do
      client.schemas.create(
        "namespace",
        {document: "", slug: "", title: "", version: "x", description: "", is_private: false}
      )
    end
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/schemas/{namespace}/{slug}",
    label: "required params",
    run: -> { client.schemas.update("slug", {namespace: "namespace"}) }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/schemas/{namespace}/{slug}",
    label: "all params",
    run: -> do
      client.schemas.update("slug", {namespace: "namespace", description: "", is_private: false, title: ""})
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/schemas/{namespace}",
    run: -> { client.schemas.list("namespace") }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/schemas/{namespace}/{slug}",
    run: -> { client.schemas.delete("slug", {namespace: "namespace"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/schemas/{namespace}/{slug}/version",
    label: "required params",
    run: -> { client.schemas.version.create("slug", {namespace: "namespace", document: "", version: "x"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/schemas/{namespace}/{slug}/version",
    label: "all params",
    run: -> do
      client.schemas.version.create(
        "slug",
        {namespace: "namespace", document: "", version: "x", force: false}
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/schemas/{namespace}/{slug}/version/{semver}",
    run: -> { client.schemas.version.retrieve("semver", {namespace: "namespace", slug: "slug"}) }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/schemas/{namespace}/{slug}/version/{semver}",
    run: -> { client.schemas.version.delete("semver", {namespace: "namespace", slug: "slug"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/schemas/{namespace}/{slug}/access-group",
    run: -> { client.schemas.access_group.create("slug", {access_group_slug: "x", namespace: "namespace"}) }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/schemas/{namespace}/{slug}/access-group",
    run: -> { client.schemas.access_group.delete("slug", {access_group_slug: "x", namespace: "namespace"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/login-portals",
    run: -> do
      client.login_portals.create(
        {
          email: {
            "logo" => "",
            "logoSize" => "100",
            "buttonText" => "Login",
            "message" => "Click to access private documentation hosted by scalar.com",
            "title" => "Private Docs",
            "mainColor" => "\#2a2f45",
            "mainBackground" => "\#f6f6f6",
            "cardColor" => "\#2a2f45",
            "cardBackground" => "\#fff",
            "buttonColor" => "\#fff",
            "buttonBackground" => "\#0f0f0f"
          },
          page: {
            "title" => "Scalar Private Docs",
            "description" => "Login to access your documentation",
            "head" => "",
            "script" => "",
            "theme" => "",
            "companyName" => "",
            "logo" => "",
            "logoURL" => "",
            "favicon" => "",
            "termsLink" => "",
            "privacyLink" => "",
            "formTitle" => "Scalar Private Docs",
            "formDescription" => "Login to access your documentation",
            "formImage" => ""
          },
          slug: "",
          title: ""
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/login-portals/{slug}",
    run: -> { client.login_portals.retrieve("slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/login-portals/{slug}",
    label: "required params",
    run: -> { client.login_portals.update("slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/login-portals/{slug}",
    label: "all params",
    run: -> { client.login_portals.update("slug", {title: ""}) }
  },
  {operation: "list", method: "GET", path: "/v1/login-portals", run: -> { client.login_portals.list }},
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/login-portals/{slug}",
    run: -> { client.login_portals.delete("slug") }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/access-groups",
    label: "required params",
    run: -> { client.access_groups.create }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/access-groups",
    label: "all params",
    run: -> { client.access_groups.create({allowed_domains: {}, name: "", slug: "x"}) }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/access-groups/{slug}",
    run: -> { client.access_groups.retrieve("slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/access-groups/{slug}",
    label: "required params",
    run: -> { client.access_groups.update("path_slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/access-groups/{slug}",
    label: "all params",
    run: -> { client.access_groups.update("path_slug", {name: "", body_slug: "x"}) }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/access-groups/{slug}",
    run: -> { client.access_groups.delete("slug") }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/access-groups/{slug}/domains",
    run: -> { client.access_groups.domains.create("slug", {domain: ""}) }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/access-groups/{slug}/domains",
    run: -> { client.access_groups.domains.delete("slug", {domain: ""}) }
  },
  {
    operation: "createRuleset",
    method: "POST",
    path: "/v1/rulesets/{namespace}",
    label: "required params",
    run: -> { client.rules.create_ruleset("namespace", {document: "", slug: "", title: ""}) }
  },
  {
    operation: "createRuleset",
    method: "POST",
    path: "/v1/rulesets/{namespace}",
    label: "all params",
    run: -> do
      client.rules.create_ruleset(
        "namespace",
        {document: "", slug: "", title: "", description: "", is_private: false}
      )
    end
  },
  {
    operation: "createRulesetAccessGroup",
    method: "POST",
    path: "/v1/rulesets/{namespace}/{slug}/access-group",
    run: -> do
      client.rules.create_ruleset_access_group("slug", {access_group_slug: "x", namespace: "namespace"})
    end
  },
  {
    operation: "deleteRuleset",
    method: "DELETE",
    path: "/v1/rulesets/{namespace}/{slug}",
    run: -> { client.rules.delete_ruleset("slug", {namespace: "namespace"}) }
  },
  {
    operation: "deleteRulesetAccessGroup",
    method: "DELETE",
    path: "/v1/rulesets/{namespace}/{slug}/access-group",
    run: -> do
      client.rules.delete_ruleset_access_group("slug", {access_group_slug: "x", namespace: "namespace"})
    end
  },
  {
    operation: "listRulesets",
    method: "GET",
    path: "/v1/rulesets/{namespace}",
    run: -> { client.rules.list_rulesets("namespace") }
  },
  {
    operation: "retrieveRulesetDocument",
    method: "GET",
    path: "/v1/rulesets/{namespace}/{slug}",
    run: -> { client.rules.retrieve_ruleset_document("slug", {namespace: "namespace"}) }
  },
  {
    operation: "updateRuleset",
    method: "PATCH",
    path: "/v1/rulesets/{namespace}/{slug}",
    label: "required params",
    run: -> { client.rules.update_ruleset("path_slug", {path_namespace: "path_namespace"}) }
  },
  {
    operation: "updateRuleset",
    method: "PATCH",
    path: "/v1/rulesets/{namespace}/{slug}",
    label: "all params",
    run: -> do
      client.rules.update_ruleset(
        "path_slug",
        {
          path_namespace: "path_namespace",
          description: "",
          is_private: false,
          body_namespace: "",
          body_slug: "",
          title: ""
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/themes",
    label: "required params",
    run: -> { client.themes.create({document: "", name: "", slug: ""}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/themes",
    label: "all params",
    run: -> { client.themes.create({document: "", name: "", slug: "", description: ""}) }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/themes/{slug}",
    run: -> { client.themes.retrieve("slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/themes/{slug}",
    label: "required params",
    run: -> { client.themes.update("slug") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/themes/{slug}",
    label: "all params",
    run: -> { client.themes.update("slug", {description: "", name: ""}) }
  },
  {operation: "list", method: "GET", path: "/v1/themes", run: -> { client.themes.list }},
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/themes/{slug}",
    run: -> { client.themes.delete("slug") }
  },
  {
    operation: "replaceDocument",
    method: "PUT",
    path: "/v1/themes/{slug}",
    run: -> { client.themes.replace_document("slug", {document: ""}) }
  },
  {operation: "list", method: "GET", path: "/v1/teams", run: -> { client.teams.list }},
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/teams/members/{uid}",
    run: -> { client.teams.members.update("uidxx", {role: "owner"}) }
  },
  {operation: "list", method: "GET", path: "/v1/teams/members", run: -> { client.teams.members.list }},
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/teams/members/{uid}",
    run: -> { client.teams.members.delete("uidxx") }
  },
  {
    operation: "cancel",
    method: "DELETE",
    path: "/v1/teams/invites/{uid}",
    run: -> { client.teams.invites.cancel("uidxx") }
  },
  {
    operation: "member",
    method: "POST",
    path: "/v1/teams/invites",
    run: -> { client.teams.invites.member({email: "user@example.com", role: "owner"}) }
  },
  {
    operation: "resend",
    method: "PATCH",
    path: "/v1/teams/invites/{uid}",
    run: -> { client.teams.invites.resend("uidxx") }
  },
  {
    operation: "createGuide",
    method: "POST",
    path: "/v1/guides",
    label: "required params",
    run: -> do
      client.scalar_docs.create_guide({allowed_domains: [], allowed_users: [], is_private: false, name: ""})
    end
  },
  {
    operation: "createGuide",
    method: "POST",
    path: "/v1/guides",
    label: "all params",
    run: -> do
      client.scalar_docs.create_guide(
        {allowed_domains: [], allowed_users: [], is_private: false, name: "", slug: "x"}
      )
    end
  },
  {
    operation: "createProject",
    method: "POST",
    path: "/v1/docs",
    label: "required params",
    run: -> { client.scalar_docs.create_project({name: "", provider: "forgejo"}) }
  },
  {
    operation: "createProject",
    method: "POST",
    path: "/v1/docs",
    label: "all params",
    run: -> do
      client.scalar_docs.create_project(
        {
          name: "",
          provider: "forgejo",
          bitbucket_repository: {
            "workspaceUuid" => "",
            "repoUuid" => ""
          },
          blank: false,
          github_repository: {
            "installationId" => 0,
            "repoId" => 0
          },
          is_private: false,
          slug: "x"
        }
      )
    end
  },
  {
    operation: "deleteProject",
    method: "DELETE",
    path: "/v1/docs/{slug}",
    run: -> { client.scalar_docs.delete_project("slug") }
  },
  {operation: "listGuides", method: "GET", path: "/v1/guides", run: -> { client.scalar_docs.list_guides }},
  {
    operation: "listProjectConfig",
    method: "GET",
    path: "/v1/docs/{slug}/config",
    label: "required params",
    run: -> { client.scalar_docs.list_project_config("slug") }
  },
  {
    operation: "listProjectConfig",
    method: "GET",
    path: "/v1/docs/{slug}/config",
    label: "all params",
    run: -> { client.scalar_docs.list_project_config("slug", {ref: "ref"}) }
  },
  {
    operation: "listProjectDomain",
    method: "GET",
    path: "/v1/docs/{slug}/domain",
    run: -> { client.scalar_docs.list_project_domain("slug") }
  },
  {
    operation: "listProjectDomainStatus",
    method: "GET",
    path: "/v1/docs/{slug}/domain/status",
    run: -> { client.scalar_docs.list_project_domain_status("slug") }
  },
  {
    operation: "listProjects",
    method: "GET",
    path: "/v1/docs",
    label: "required params",
    run: -> { client.scalar_docs.list_projects }
  },
  {
    operation: "listProjects",
    method: "GET",
    path: "/v1/docs",
    label: "all params",
    run: -> { client.scalar_docs.list_projects({limit: 1}) }
  },
  {
    operation: "publishGuide",
    method: "POST",
    path: "/v1/guides/{slug}/publish",
    run: -> { client.scalar_docs.publish_guide("slug") }
  },
  {
    operation: "publishProject",
    method: "POST",
    path: "/v1/docs/{slug}/publish",
    label: "required params",
    run: -> { client.scalar_docs.publish_project("slug") }
  },
  {
    operation: "publishProject",
    method: "POST",
    path: "/v1/docs/{slug}/publish",
    label: "all params",
    run: -> do
      client.scalar_docs.publish_project("slug", {commit_sha: "", config_path: "", preview: false})
    end
  },
  {
    operation: "retrieveProject",
    method: "GET",
    path: "/v1/docs/{slug}",
    run: -> { client.scalar_docs.retrieve_project("slug") }
  },
  {
    operation: "updateProject",
    method: "PATCH",
    path: "/v1/docs/{slug}",
    label: "required params",
    run: -> { client.scalar_docs.update_project("slug") }
  },
  {
    operation: "updateProject",
    method: "PATCH",
    path: "/v1/docs/{slug}",
    label: "all params",
    run: -> do
      client.scalar_docs.update_project(
        "slug",
        {
          access_groups: ["xxxxx"],
          active_theme_id: "xxxxx",
          agent_enabled: false,
          analytics_enabled: false,
          is_private: false,
          login_portal_uid: "xxxxx",
          name: ""
        }
      )
    end
  },
  {
    operation: "updateProjectConfig",
    method: "PUT",
    path: "/v1/docs/{slug}/config",
    label: "required params",
    run: -> { client.scalar_docs.update_project_config("slug", {content: ""}) }
  },
  {
    operation: "updateProjectConfig",
    method: "PUT",
    path: "/v1/docs/{slug}/config",
    label: "all params",
    run: -> do
      client.scalar_docs.update_project_config(
        "slug",
        {content: "", base_token: "", message: "", path: "", ref: ""}
      )
    end
  },
  {operation: "list", method: "GET", path: "/v1/namespaces", run: -> { client.namespaces.list }},
  {
    operation: "exchangePersonalToken",
    method: "POST",
    path: "/v1/auth/exchange",
    run: -> { client.authentication.exchange_personal_token({personal_token: ""}) }
  },
  {
    operation: "listCurrentUser",
    method: "GET",
    path: "/v1/auth/me",
    run: -> { client.authentication.list_current_user }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/sdks",
    label: "required params",
    run: -> { client.sdks.create({api_uid: "xxxxx", languages: ["typescript"]}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/sdks",
    label: "all params",
    run: -> do
      client.sdks.create(
        {api_uid: "xxxxx", languages: ["typescript"], class_name: "", config: "", slug: "x", title: ""}
      )
    end
  },
  {operation: "retrieve", method: "GET", path: "/v1/sdks/{uid}", run: -> { client.sdks.retrieve("uidxx") }},
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/sdks/{uid}",
    label: "required params",
    run: -> { client.sdks.update("uidxx") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/sdks/{uid}",
    label: "all params",
    run: -> do
      client.sdks.update(
        "uidxx",
        {api_uid: "xxxxx", api_version: "", config: "", is_private: false, slug: "x", title: ""}
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/sdks",
    label: "required params",
    run: -> { client.sdks.list }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/sdks",
    label: "all params",
    run: -> { client.sdks.list({limit: 1}) }
  },
  {operation: "delete", method: "DELETE", path: "/v1/sdks/{uid}", run: -> { client.sdks.delete("uidxx") }},
  {
    operation: "build",
    method: "POST",
    path: "/v1/sdks/{uid}/build",
    label: "required params",
    run: -> { client.sdks.build("uidxx") }
  },
  {
    operation: "build",
    method: "POST",
    path: "/v1/sdks/{uid}/build",
    label: "all params",
    run: -> { client.sdks.build("uidxx", {languages: ["typescript"], version: ""}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/sdks/{uid}/versions",
    run: -> { client.sdks.versions.create("uidxx", {api_version: "", version: ""}) }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/sdks/{uid}/versions/{version}",
    run: -> { client.sdks.versions.delete("version", {uid: "uidxx"}) }
  },
  {
    operation: "link",
    method: "POST",
    path: "/v1/sdks/{uid}/repositories",
    label: "required params",
    run: -> do
      client.sdks.repositories.link("uidxx", {base_branch: "", language: "typescript", repository_id: 0})
    end
  },
  {
    operation: "link",
    method: "POST",
    path: "/v1/sdks/{uid}/repositories",
    label: "all params",
    run: -> do
      client.sdks.repositories.link(
        "uidxx",
        {base_branch: "", language: "typescript", repository_id: 0, prerelease_type: ""}
      )
    end
  },
  {
    operation: "unlink",
    method: "DELETE",
    path: "/v1/sdks/{uid}/repositories/{language}",
    run: -> { client.sdks.repositories.unlink("typescript", {uid: "uidxx"}) }
  },
  {
    operation: "updatePublishing",
    method: "POST",
    path: "/v1/sdks/{uid}/repositories/{language}/publishing",
    label: "required params",
    run: -> do
      client.sdks.repositories.update_publishing("typescript", {uid: "uidxx", publish_on_merge: false})
    end
  },
  {
    operation: "updatePublishing",
    method: "POST",
    path: "/v1/sdks/{uid}/repositories/{language}/publishing",
    label: "all params",
    run: -> do
      client.sdks.repositories.update_publishing(
        "typescript",
        {uid: "uidxx", publish_on_merge: false, access: "public", auth_method: "oidc", tag: ""}
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/mcp/servers",
    label: "required params",
    run: -> { client.mcp.servers.create({name: "x"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/mcp/servers",
    label: "all params",
    run: -> { client.mcp.servers.create({name: "x", project_uids: [""], slug: "x", version_uids: [""]}) }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/mcp/servers/{id}",
    run: -> { client.mcp.servers.retrieve("id") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/mcp/servers/{id}",
    label: "required params",
    run: -> { client.mcp.servers.update("id") }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/mcp/servers/{id}",
    label: "all params",
    run: -> do
      client.mcp.servers.update(
        "id",
        {auto_add_operations: false, docs_pages: [""], name: "x", operations: [""], slug: "x"}
      )
    end
  },
  {operation: "list", method: "GET", path: "/v1/mcp/servers", run: -> { client.mcp.servers.list }},
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/mcp/servers/{id}",
    run: -> { client.mcp.servers.delete("id") }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/mcp/servers/{id}/installations",
    label: "required params",
    run: -> { client.mcp.servers.installations.create("id", {document_auth: {}, name: "x"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/mcp/servers/{id}/installations",
    label: "all params",
    run: -> { client.mcp.servers.installations.create("id", {document_auth: {}, name: "x", slug: "x"}) }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/mcp/servers/{id}/installations/{installationId}",
    run: -> { client.mcp.servers.installations.retrieve("installation_id", {id: "id"}) }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/mcp/servers/{id}/installations/{installationId}",
    label: "required params",
    run: -> { client.mcp.servers.installations.update("installation_id", {id: "id"}) }
  },
  {
    operation: "update",
    method: "PATCH",
    path: "/v1/mcp/servers/{id}/installations/{installationId}",
    label: "all params",
    run: -> do
      client.mcp.servers.installations.update(
        "installation_id",
        {
          id: "id",
          document_auth: {},
          is_private: false,
          login_portal_uid: "",
          mcp_version: "",
          name: "x",
          slug: "x"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/mcp/servers/{id}/installations",
    run: -> { client.mcp.servers.installations.list("id") }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/mcp/servers/{id}/installations/{installationId}",
    run: -> { client.mcp.servers.installations.delete("installation_id", {id: "id"}) }
  },
  {
    operation: "createAccessGroup",
    method: "POST",
    path: "/v1/mcp/servers/{id}/installations/{installationId}/access-group",
    run: -> do
      client.mcp.servers.installations.create_access_group(
        "installation_id",
        {id: "id", access_group_uid: "xxxxx"}
      )
    end
  },
  {
    operation: "deleteAccessGroup",
    method: "DELETE",
    path: "/v1/mcp/servers/{id}/installations/{installationId}/access-group",
    run: -> do
      client.mcp.servers.installations.delete_access_group(
        "installation_id",
        {id: "id", access_group_uid: "xxxxx"}
      )
    end
  },
  {
    operation: "oauthAuthorizationServerMetadata",
    method: "GET",
    path: "/.well-known/oauth-authorization-server",
    run: -> { client.o_auth.oauth_authorization_server_metadata }
  },
  {
    operation: "oauthAuthorize",
    method: "GET",
    path: "/v1/oauth/authorize",
    run: -> { client.o_auth.oauth_authorize }
  },
  {
    operation: "oauthRevoke",
    method: "POST",
    path: "/v1/oauth/revoke",
    label: "required params",
    run: -> { client.o_auth.oauth_revoke({token: ""}) }
  },
  {
    operation: "oauthRevoke",
    method: "POST",
    path: "/v1/oauth/revoke",
    label: "all params",
    run: -> do
      client.o_auth.oauth_revoke({token: "", client_id: "", client_secret: "", token_type_hint: ""})
    end
  },
  {
    operation: "oauthToken",
    method: "POST",
    path: "/v1/oauth/token",
    label: "required params",
    run: -> { client.o_auth.oauth_token({grant_type: ""}) }
  },
  {
    operation: "oauthToken",
    method: "POST",
    path: "/v1/oauth/token",
    label: "all params",
    run: -> do
      client.o_auth.oauth_token(
        {
          grant_type: "",
          client_id: "",
          client_secret: "",
          code: "",
          code_verifier: "",
          redirect_uri: "",
          refresh_token: "",
          scope: ""
        }
      )
    end
  }
]

# Renders a failure as its whole cause chain, then the backtrace of the exception that escaped.
# The SDK wraps a dropped socket in an APIConnectionError whose message is only "Connection
# error." — the Errno::ECONNRESET or EOFError that says which teardown it was is attached as
# `cause` and is invisible unless walked. The chain leads so that a report reader taking only the
# first line still sees the class and message of the failure itself.
def error_details(e)
  chain = []
  current = e
  # Ruby refuses to set a circular `cause`, so following it always terminates.
  while current
    chain << "#{current.class.name}: #{current.message}"
    current = current.cause
  end
  (chain + e.backtrace.to_a).join("\n")
end

def run_case(test_case)
  started_at = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  # `label` distinguishes the required-params run from the all-params run of the same operation;
  # it is absent entirely when the operation contributed only one case.
  identity = {operation: test_case[:operation], method: test_case[:method], path: test_case[:path]}
  identity[:label] = test_case[:label] if test_case[:label]
  begin
    test_case[:run].call
    identity.merge(
      status: "passed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i
    )
  rescue StandardError => e
    identity.merge(
      status: "failed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i,
      error: error_details(e)
    )
  end
end

filter = ENV["SCALAR_SMOKE_FILTER"]
needles = filter ? filter.split(",").map(&:strip).reject(&:empty?) : []
selected =
  (
    if needles.empty?
      cases
    else
      cases.select do |test_case|
        needles.any? { |needle| test_case[:operation].include?(needle) || test_case[:path].include?(needle) }
      end
    end
  )

# Run the cases under a bounded worker pool rather than one thread per case. A large SDK has
# hundreds of operations, and starting a thread for each one puts more requests in flight than
# the client's connection pool has slots while the runner is already busy with other targets.
# SCALAR_SMOKE_CONCURRENCY overrides the cap; anything unparseable falls back to the default.
# Workers pull from a shared cursor and write into a pre-sized array, so results stay in case
# order however the threads interleave.
concurrency = [Integer(ENV.fetch("SCALAR_SMOKE_CONCURRENCY", "32"), exception: false) || 32, 1].max
worker_count = [concurrency, selected.length].min
results = Array.new(selected.length)
cursor = 0
mutex = Mutex.new
Array
  .new(worker_count) do
    Thread.new do
      loop do
        index = mutex.synchronize { cursor.tap { cursor += 1 } }
        break if index >= selected.length
        results[index] = run_case(selected[index])
      end
    end
  end
  .each(&:join)

failed = results.select { |result| result[:status] == "failed" }
if ENV["SCALAR_SMOKE_REPORT"]
  File.write(
    ENV.fetch("SCALAR_SMOKE_REPORT"),
    JSON.generate({total: results.length, failed: failed.length, results: results})
  )
else
  results.each do |result|
    suffix = result[:label] ? " [#{result[:label]}]" : ""
    if result[:status] == "passed"
      puts "PASS #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]}) #{result[:durationMs]}ms"
    else
      warn "FAIL #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]})\n#{result[:error]}"
    end
  end
  warn "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing)." if results.empty?
  puts "\n#{results.length - failed.length}/#{results.length} samples passed" unless results.empty?
end

exit(1) if failed.any? || results.empty?
