# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) && caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "scalar-ruby/version"
require_relative "scalar-ruby/internal/util"
require_relative "scalar-ruby/internal/type/converter"
require_relative "scalar-ruby/internal/type/unknown"
require_relative "scalar-ruby/internal/type/boolean"
require_relative "scalar-ruby/internal/type/file_input"
require_relative "scalar-ruby/internal/type/enum"
require_relative "scalar-ruby/internal/type/union"
require_relative "scalar-ruby/internal/type/array_of"
require_relative "scalar-ruby/internal/type/hash_of"
require_relative "scalar-ruby/internal/type/base_model"
require_relative "scalar-ruby/internal/type/base_page"
require_relative "scalar-ruby/internal/type/request_parameters"
require_relative "scalar-ruby/internal"
require_relative "scalar-ruby/request_options"
require_relative "scalar-ruby/file_part"
require_relative "scalar-ruby/errors"
require_relative "scalar-ruby/internal/transport/base_client"
require_relative "scalar-ruby/internal/transport/pooled_net_requester"
require_relative "scalar-ruby/client"
require_relative "scalar-ruby/models/access_group"
require_relative "scalar-ruby/models/400"
require_relative "scalar-ruby/models/401"
require_relative "scalar-ruby/models/403"
require_relative "scalar-ruby/models/404"
require_relative "scalar-ruby/models/422"
require_relative "scalar-ruby/models/500"
require_relative "scalar-ruby/models/authentication_exchange_personal_token_params"
require_relative "scalar-ruby/models/authentication_exchange_personal_token_response"
require_relative "scalar-ruby/models/authentication_list_current_user_params"
require_relative "scalar-ruby/models/authentication_list_current_user_response"
require_relative "scalar-ruby/models/login_portal_create_params"
require_relative "scalar-ruby/models/login_portal_delete_params"
require_relative "scalar-ruby/models/login_portal_email"
require_relative "scalar-ruby/models/login_portal_list_params"
require_relative "scalar-ruby/models/login_portal_list_response"
require_relative "scalar-ruby/models/login_portal_page"
require_relative "scalar-ruby/models/login_portal_retrieve_params"
require_relative "scalar-ruby/models/login_portal_retrieve_response"
require_relative "scalar-ruby/models/login_portal_update_params"
require_relative "scalar-ruby/models/managed_doc_version"
require_relative "scalar-ruby/models/namespace"
require_relative "scalar-ruby/models/namespace_list_params"
require_relative "scalar-ruby/models/namespace_list_response"
require_relative "scalar-ruby/models/nanoid"
require_relative "scalar-ruby/models/registry_create_api_document_access_group_params"
require_relative "scalar-ruby/models/registry_create_api_document_params"
require_relative "scalar-ruby/models/registry_create_api_document_response"
require_relative "scalar-ruby/models/registry_create_api_document_version_params"
require_relative "scalar-ruby/models/registry_delete_api_document_access_group_params"
require_relative "scalar-ruby/models/registry_delete_api_document_params"
require_relative "scalar-ruby/models/registry_delete_api_document_version_params"
require_relative "scalar-ruby/models/registry_list_all_api_documents_params"
require_relative "scalar-ruby/models/registry_list_all_api_documents_response"
require_relative "scalar-ruby/models/registry_list_api_documents_params"
require_relative "scalar-ruby/models/registry_list_api_documents_response"
require_relative "scalar-ruby/models/registry_list_api_document_version_metadata_params"
require_relative "scalar-ruby/models/registry_retrieve_api_document_version_params"
require_relative "scalar-ruby/models/registry_retrieve_api_document_version_response"
require_relative "scalar-ruby/models/registry_update_api_document_params"
require_relative "scalar-ruby/models/registry_update_api_document_version_params"
require_relative "scalar-ruby/models/registry_update_api_document_version_response"
require_relative "scalar-ruby/models/rule_create_ruleset_access_group_params"
require_relative "scalar-ruby/models/rule_create_ruleset_params"
require_relative "scalar-ruby/models/rule_delete_ruleset_access_group_params"
require_relative "scalar-ruby/models/rule_delete_ruleset_params"
require_relative "scalar-ruby/models/rule_list_rulesets_params"
require_relative "scalar-ruby/models/rule_list_rulesets_response"
require_relative "scalar-ruby/models/rule_retrieve_ruleset_document_params"
require_relative "scalar-ruby/models/rule_retrieve_ruleset_document_response"
require_relative "scalar-ruby/models/rule_update_ruleset_params"
require_relative "scalar-ruby/models/scalar_doc_create_guide_params"
require_relative "scalar-ruby/models/scalar_doc_create_guide_response"
require_relative "scalar-ruby/models/scalar_doc_list_guides_params"
require_relative "scalar-ruby/models/scalar_doc_list_guides_response"
require_relative "scalar-ruby/models/scalar_doc_publish_guide_params"
require_relative "scalar-ruby/models/scalar_doc_publish_guide_response"
require_relative "scalar-ruby/models/schema_create_params"
require_relative "scalar-ruby/models/schema_delete_params"
require_relative "scalar-ruby/models/schema_list_params"
require_relative "scalar-ruby/models/schema_list_response"
require_relative "scalar-ruby/models/schemas/access_group_create_params"
require_relative "scalar-ruby/models/schemas/access_group_delete_params"
require_relative "scalar-ruby/models/schemas/version_create_params"
require_relative "scalar-ruby/models/schemas/version_delete_params"
require_relative "scalar-ruby/models/schemas/version_retrieve_params"
require_relative "scalar-ruby/models/schemas/version_retrieve_response"
require_relative "scalar-ruby/models/schema_update_params"
require_relative "scalar-ruby/models/slug"
require_relative "scalar-ruby/models/team_list_params"
require_relative "scalar-ruby/models/team_list_response"
require_relative "scalar-ruby/models/theme_create_params"
require_relative "scalar-ruby/models/theme_delete_params"
require_relative "scalar-ruby/models/theme_list_params"
require_relative "scalar-ruby/models/theme_list_response"
require_relative "scalar-ruby/models/theme_replace_document_params"
require_relative "scalar-ruby/models/theme_retrieve_params"
require_relative "scalar-ruby/models/theme_retrieve_response"
require_relative "scalar-ruby/models/theme_update_params"
require_relative "scalar-ruby/models/timestamp"
require_relative "scalar-ruby/models/uid"
require_relative "scalar-ruby/models/version"
require_relative "scalar-ruby/models"
require_relative "scalar-ruby/resources/registry"
require_relative "scalar-ruby/resources/schemas"
require_relative "scalar-ruby/resources/schemas/version"
require_relative "scalar-ruby/resources/schemas/access_group"
require_relative "scalar-ruby/resources/login_portals"
require_relative "scalar-ruby/resources/rules"
require_relative "scalar-ruby/resources/themes"
require_relative "scalar-ruby/resources/teams"
require_relative "scalar-ruby/resources/scalar_docs"
require_relative "scalar-ruby/resources/namespaces"
require_relative "scalar-ruby/resources/authentication"
