module Scalar
  module Models
    type github_project =
      {
        access_groups: top,
        active_deployment: Scalar::ActiveDeployment?,
        active_theme_id: String,
        agent_enabled: bool,
        analytics_enabled: bool,
        created_at: Integer,
        is_private: bool,
        last_published: Integer?,
        last_published_uid: String?,
        login_portal_uid: String,
        name: String,
        publish_message: String,
        publish_status: String,
        slug: String,
        uid: String,
        updated_at: Integer,
        user_info_hook_url: String,
        repository: Scalar::GithubProjectRepository?,
        typesense_id: Float
      }

    class GithubProject < Scalar::Internal::Type::BaseModel
      attr_accessor access_groups: top

      attr_accessor active_deployment: Scalar::ActiveDeployment?

      attr_accessor active_theme_id: String

      attr_accessor agent_enabled: bool

      attr_accessor analytics_enabled: bool

      attr_accessor created_at: Integer

      attr_accessor is_private: bool

      attr_accessor last_published: Integer?

      attr_accessor last_published_uid: String?

      attr_accessor login_portal_uid: String

      attr_accessor name: String

      attr_accessor publish_message: String

      attr_accessor publish_status: String

      attr_accessor slug: String

      attr_accessor uid: String

      attr_accessor updated_at: Integer

      attr_accessor user_info_hook_url: String

      attr_accessor repository: Scalar::GithubProjectRepository?

      attr_reader typesense_id: Float?

      def typesense_id=: (Float) -> Float

      def initialize: (
        access_groups: top,
        active_deployment: Scalar::ActiveDeployment?,
        active_theme_id: String,
        agent_enabled: bool,
        analytics_enabled: bool,
        created_at: Integer,
        is_private: bool,
        last_published: Integer?,
        last_published_uid: String?,
        login_portal_uid: String,
        name: String,
        publish_message: String,
        publish_status: String,
        slug: String,
        uid: String,
        updated_at: Integer,
        user_info_hook_url: String,
        ?repository: Scalar::GithubProjectRepository?,
        ?typesense_id: Float
      ) -> void

      def to_hash: -> {
        access_groups: top,
        active_deployment: Scalar::ActiveDeployment?,
        active_theme_id: String,
        agent_enabled: bool,
        analytics_enabled: bool,
        created_at: Integer,
        is_private: bool,
        last_published: Integer?,
        last_published_uid: String?,
        login_portal_uid: String,
        name: String,
        publish_message: String,
        publish_status: String,
        slug: String,
        uid: String,
        updated_at: Integer,
        user_info_hook_url: String,
        repository: Scalar::GithubProjectRepository?,
        typesense_id: Float
      }
    end
  end
end
