module Scalar
  module Models
    type method_ =
      :delete
      | :get
      | :head
      | :options
      | :patch
      | :post
      | :put
      | :query
      | :trace

    module Method
      extend Scalar::Internal::Type::Enum

      DELETE: :delete
      GET: :get
      HEAD: :head
      OPTIONS: :options
      PATCH: :patch
      POST: :post
      PUT: :put
      QUERY: :query
      TRACE: :trace

      def self?.values: -> ::Array[Scalar::Models::method_]
    end
  end
end
