module Scalar
  module Models
    type o_auth_oauth_authorization_server_metadata_params =
      {  } & Scalar::Internal::Type::request_parameters

    class OAuthOauthAuthorizationServerMetadataParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      def initialize: (?request_options: Scalar::request_opts) -> void

      def to_hash: -> { request_options: Scalar::RequestOptions }
    end
  end
end
