module Scalar
  module Models
    type o_auth_oauth_token_params =
      {
        grant_type: String,
        client_id: String,
        client_secret: String,
        code: String,
        code_verifier: String,
        redirect_uri: String,
        refresh_token: String,
        scope: String
      }
      & Scalar::Internal::Type::request_parameters

    class OAuthOauthTokenParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      attr_accessor grant_type: String

      attr_reader client_id: String?

      def client_id=: (String) -> String

      attr_reader client_secret: String?

      def client_secret=: (String) -> String

      attr_reader code: String?

      def code=: (String) -> String

      attr_reader code_verifier: String?

      def code_verifier=: (String) -> String

      attr_reader redirect_uri: String?

      def redirect_uri=: (String) -> String

      attr_reader refresh_token: String?

      def refresh_token=: (String) -> String

      attr_reader scope: String?

      def scope=: (String) -> String

      def initialize: (
        grant_type: String,
        ?client_id: String,
        ?client_secret: String,
        ?code: String,
        ?code_verifier: String,
        ?redirect_uri: String,
        ?refresh_token: String,
        ?scope: String,
        ?request_options: Scalar::request_opts
      ) -> void

      def to_hash: -> {
        grant_type: String,
        client_id: String,
        client_secret: String,
        code: String,
        code_verifier: String,
        redirect_uri: String,
        refresh_token: String,
        scope: String,
        request_options: Scalar::RequestOptions
      }
    end
  end
end
