module Scalar
  module Models
    type o_auth_oauth_revoke_params =
      {
        token: String,
        client_id: String,
        client_secret: String,
        token_type_hint: String
      }
      & Scalar::Internal::Type::request_parameters

    class OAuthOauthRevokeParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      attr_accessor token: String

      attr_reader client_id: String?

      def client_id=: (String) -> String

      attr_reader client_secret: String?

      def client_secret=: (String) -> String

      attr_reader token_type_hint: String?

      def token_type_hint=: (String) -> String

      def initialize: (
        token: String,
        ?client_id: String,
        ?client_secret: String,
        ?token_type_hint: String,
        ?request_options: Scalar::request_opts
      ) -> void

      def to_hash: -> {
        token: String,
        client_id: String,
        client_secret: String,
        token_type_hint: String,
        request_options: Scalar::RequestOptions
      }
    end
  end
end
