module Scalar
  module Models
    type oauth_error = { error: String, error_description: String }

    class OauthError < Scalar::Internal::Type::BaseModel
      attr_accessor error: String

      attr_reader error_description: String?

      def error_description=: (String) -> String

      def initialize: (error: String, ?error_description: String) -> void

      def to_hash: -> { error: String, error_description: String }
    end
  end
end
