module Scalar
  module Models
    type oauth_authorization_server_metadata =
      {
        authorization_endpoint: String,
        code_challenge_methods_supported: ::Array[String],
        grant_types_supported: ::Array[String],
        issuer: String,
        response_types_supported: ::Array[String],
        revocation_endpoint: String,
        revocation_endpoint_auth_methods_supported: ::Array[String],
        scopes_supported: ::Array[String],
        token_endpoint: String,
        token_endpoint_auth_methods_supported: ::Array[String]
      }

    class OauthAuthorizationServerMetadata < Scalar::Internal::Type::BaseModel
      attr_accessor authorization_endpoint: String

      attr_accessor code_challenge_methods_supported: ::Array[String]

      attr_accessor grant_types_supported: ::Array[String]

      attr_accessor issuer: String

      attr_accessor response_types_supported: ::Array[String]

      attr_accessor revocation_endpoint: String

      attr_accessor revocation_endpoint_auth_methods_supported: ::Array[String]

      attr_accessor scopes_supported: ::Array[String]

      attr_accessor token_endpoint: String

      attr_accessor token_endpoint_auth_methods_supported: ::Array[String]

      def initialize: (
        authorization_endpoint: String,
        code_challenge_methods_supported: ::Array[String],
        grant_types_supported: ::Array[String],
        issuer: String,
        response_types_supported: ::Array[String],
        revocation_endpoint: String,
        revocation_endpoint_auth_methods_supported: ::Array[String],
        scopes_supported: ::Array[String],
        token_endpoint: String,
        token_endpoint_auth_methods_supported: ::Array[String]
      ) -> void

      def to_hash: -> {
        authorization_endpoint: String,
        code_challenge_methods_supported: ::Array[String],
        grant_types_supported: ::Array[String],
        issuer: String,
        response_types_supported: ::Array[String],
        revocation_endpoint: String,
        revocation_endpoint_auth_methods_supported: ::Array[String],
        scopes_supported: ::Array[String],
        token_endpoint: String,
        token_endpoint_auth_methods_supported: ::Array[String]
      }
    end
  end
end
