module Scalar
  module Models
    type registry_create_api_document_params =
      {
        namespace: String,
        document: String,
        slug: String,
        title: String,
        version: String,
        description: String,
        is_private: bool,
        ruleset: String
      }
      & Scalar::Internal::Type::request_parameters

    class RegistryCreateAPIDocumentParams < Scalar::Internal::Type::BaseModel
      extend Scalar::Internal::Type::RequestParameters::Converter
      include Scalar::Internal::Type::RequestParameters

      attr_accessor namespace: String

      attr_accessor document: String

      attr_accessor slug: String

      attr_accessor title: String

      attr_accessor version: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader is_private: bool?

      def is_private=: (bool) -> bool

      attr_reader ruleset: String?

      def ruleset=: (String) -> String

      def initialize: (
        namespace: String,
        document: String,
        slug: String,
        title: String,
        version: String,
        ?description: String,
        ?is_private: bool,
        ?ruleset: String,
        ?request_options: Scalar::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        document: String,
        slug: String,
        title: String,
        version: String,
        description: String,
        is_private: bool,
        ruleset: String,
        request_options: Scalar::RequestOptions
      }
    end
  end
end
