module Scalar
  module Resources
    class Rules
      def create_ruleset: (
        String namespace,
        document: String,
        slug: String,
        title: String,
        ?description: String,
        ?is_private: bool,
        ?request_options: Scalar::request_opts
      ) -> Scalar::UID

      def create_ruleset_access_group: (
        String slug,
        access_group_slug: String,
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def delete_ruleset: (
        String slug,
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def delete_ruleset_access_group: (
        String slug,
        access_group_slug: String,
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def list_rulesets: (
        String namespace,
        ?request_options: Scalar::request_opts
      ) -> ::Array[Scalar::Models::RuleListRulesetsResponseItem]

      def retrieve_ruleset_document: (
        String slug,
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> String

      def update_ruleset: (
        String path_slug,
        path_namespace: String,
        ?description: String,
        ?is_private: bool,
        ?body_namespace: String,
        ?body_slug: String,
        ?title: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def initialize: (client: Scalar::Client) -> void
    end
  end
end
