module Scalar
  module Resources
    class Schemas
      attr_reader version: Scalar::Resources::Schemas::Version

      attr_reader access_group: Scalar::Resources::Schemas::AccessGroup

      def create: (
        String namespace,
        document: String,
        slug: String,
        title: String,
        version: String,
        ?description: String,
        ?is_private: bool,
        ?request_options: Scalar::request_opts
      ) -> Scalar::UID

      def update: (
        String slug,
        namespace: String,
        ?description: String,
        ?is_private: bool,
        ?title: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def list: (
        String namespace,
        ?request_options: Scalar::request_opts
      ) -> ::Array[Scalar::Models::SchemaListResponseItem]

      def delete: (
        String slug,
        namespace: String,
        ?request_options: Scalar::request_opts
      ) -> top

      def initialize: (client: Scalar::Client) -> void
    end
  end
end
