module Scalar
  module Resources
    class Teams
      attr_reader members: Scalar::Resources::Teams::Members

      attr_reader invites: Scalar::Resources::Teams::Invites

      def list: (
        ?request_options: Scalar::request_opts
      ) -> ::Array[Scalar::Team]

      def initialize: (client: Scalar::Client) -> void
    end
  end
end
